import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const MonaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

<link rel="icon" href="/favicon.ico" sizes="any" />

export const metadata: Metadata = {
  title: "Lexi Mock Ai",
  description: "Generated by Lexi Mock Ai Interviews",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MonaSans.className} antialiased`}
      >
        {children}

        <Toaster/>
      </body>
    </html>
  );
}
